import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets:['latin'] })

export const metadata: Metadata = {
  title: "ACADEMA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" >
      <body
        className={`${inter.className} antialiased`}>
        <Toaster/>
        {children}
      </body>
    </html>
  );
}
